# Generated by Django 5.0.1 on 2024-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
