# Generated by Django 5.0.1 on 2024-02-12 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_quantity_desc'),
        ('User', '0004_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('contact_no', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('order_time', models.DateTimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user_orders')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
