# Generated by Django 5.0.1 on 2024-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_desc',
            field=models.CharField(default='1pc', max_length=30),
        ),
    ]
